OPENAI_API_KEY: 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
 * Serving Flask app 'analyze_with_gpt4v'
 * Debug mode: on
[31m[1mWARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.[0m
 * Running on all addresses (0.0.0.0)
 * Running on http://127.0.0.1:5003
 * Running on http://192.168.0.102:5003
[33mPress CTRL+C to quit[0m
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 904-880-343
OPENAI_API_KEY: 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
/Users/shuuregulus7/anaconda3/lib/python3.11/multiprocessing/resource_tracker.py:224: UserWarning: resource_tracker: There appear to be 1 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
